image: python:alpine

pages:
  script:
    - pip install sphinx
    - apk --no-cache add make
    - cd docs; make html
    - mv docs/build/html public/
  artifacts:
    paths:
      - public
  only:
    - master
